#!/bin/sh
set -e
if [ ! -e /var/lib/emacsen-common/state/package/installed/emacsen-common ]; then
    # Fallback to emacsen-common 1.x
    if [ "$1" = "configure" ] && [ -x /usr/lib/emacsen-common/emacs-package-install ]; then
    /usr/lib/emacsen-common/emacs-package-install emacs-mozc
    fi
else
# Automatically added by dh_installemacsen/12.1.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-install ] ; then
		/usr/lib/emacsen-common/emacs-package-install --postinst emacs-mozc
	fi
fi
# End automatically added section

fi
