#!/bin/sh
set -e
if [ ! -e /var/lib/emacsen-common/state/package/installed/emacsen-common ]; then
    # Fallback to emacsen-common 1.x
    if [ -x /usr/lib/emacsen-common/emacs-package-remove ]; then
    /usr/lib/emacsen-common/emacs-package-remove emacs-mozc
    fi
else
# Automatically added by dh_installemacsen/12.1.1
if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-remove ] ; then
	/usr/lib/emacsen-common/emacs-package-remove --prerm emacs-mozc
fi
# End automatically added section

fi
