#!/usr/bin/dh-exec --with-scripts=subst-multiarch,install-rename
# module
src/out_linux/Release/fcitx-mozc.so usr/lib/${DEB_HOST_MULTIARCH}/fcitx/
# mo
src/out_linux/Release/gen/unix/fcitx/po/ja.mo => usr/share/locale/ja/LC_MESSAGES/fcitx-mozc.mo
src/out_linux/Release/gen/unix/fcitx/po/zh_TW.mo => usr/share/locale/zh_TW/LC_MESSAGES/fcitx-mozc.mo
src/out_linux/Release/gen/unix/fcitx/po/zh_CN.mo => usr/share/locale/zh_CN/LC_MESSAGES/fcitx-mozc.mo
# config files
src/unix/fcitx/fcitx-mozc.conf usr/share/fcitx/addon/
src/unix/fcitx/mozc.conf usr/share/fcitx/inputmethod/
