name: CI for macOS
# https://github.com/google/mozc/blob/master/docs/build_mozc_in_osx.md

# Run on push.
on: push

# Prevent previous workflows from running.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
    runs-on: macos-11
    timeout-minutes: 60

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: setup
        working-directory: ./src/third_party
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" >> $GITHUB_PATH
          python3 -m pip install six
          cd gyp
          git apply ../../gyp/gyp.patch

      - name: build
        working-directory: ./src
        run: |
          python3 ./build_mozc.py gyp --noqt
          python3 ./build_mozc.py build mac/mac.gyp:GoogleJapaneseInput
